spring:
  datasource:
    url: jdbc:mysql://localhost:3306/demo_api?createDatabaseIfNotExist=true
    username: root
    password: dilip@123
  jpa:
    show-sql: true
websiteUrl: http://localhost:4242
